export const queryKeys = {
  health: ["health"] as const,
  healthReady: ["health", "ready"] as const,
  brands: ["catalog", "brands"] as const,
  categories: ["catalog", "categories"] as const,
  categoryTree: ["catalog", "category-tree"] as const,
  products: (params?: unknown) => ["catalog", "products", params] as const,
  featured: ["catalog", "featured"] as const,
  newest: ["catalog", "newest"] as const,
  refurbished: ["catalog", "refurbished"] as const,
  flash: ["catalog", "flash"] as const,
  product: (idOrSlug: string) => ["catalog", "product", idOrSlug] as const,
  cart: ["cart"] as const,
  cartProductMeta: ["cart", "product-meta"] as const,
  wishlist: ["wishlist"] as const,
  wishlistProductMeta: ["wishlist", "product-meta"] as const,
  orders: ["orders"] as const,
  order: (id: string) => ["orders", id] as const,
  orderPayments: (orderId: string) => ["orders", orderId, "payments"] as const,
  paymentRefunds: (paymentId: string) =>
    ["payments", paymentId, "refunds"] as const,
  payment: (id: string) => ["payments", id] as const,
  paymentsHistory: (params?: unknown) => ["payments", "history", params] as const,
  cancellationReasons: ["orders", "cancellation-reasons"] as const,
  addresses: ["addresses"] as const,
  warehouses: ["inventory", "warehouses"] as const,
  shippingMethods: ["shipping", "methods"] as const,
  shippingEstimate: (params?: unknown) =>
    ["shipping", "estimate", params] as const,
  deliverySlots: ["shipping", "delivery-slots"] as const,
  pickupPoints: ["shipping", "pickup-points"] as const,
  paymentMethods: ["payments", "methods"] as const,
  checkoutCoupon: (code?: string) => ["checkout", "coupon", code] as const,
  couponsAvailable: ["coupons", "available"] as const,
  couponApplied: ["coupons", "applied"] as const,
  me: ["auth", "me"] as const,
  banners: ["marketing", "banners"] as const,
  navigation: ["marketing", "navigation"] as const,
  recommendations: (params?: unknown) => ["marketing", "recommendations", params] as const,
  adminOrders: (params?: unknown) => ["admin", "orders", params] as const,
  adminProducts: (params?: unknown) => ["admin", "products", params] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminInventory: ["admin", "inventory"] as const,
};
