/** Central path registry — keep in sync with Nest controllers under /api */

export const endpoints = {
  health: {
    root: "/health",
    live: "/health/live",
    ready: "/health/ready",
    db: "/health/db",
    redis: "/health/redis",
    storage: "/health/storage",
    queues: "/health/queues",
  },
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
    profile: "/auth/profile",
    changePassword: "/auth/change-password",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    sendOtp: "/auth/send-otp",
    verifyOtp: "/auth/verify-otp",
    sessions: "/auth/sessions",
    session: (id: string) => `/auth/sessions/${id}`,
    firebase: "/auth/firebase",
  },
  catalog: {
    brands: "/catalog/brands",
    productTypes: "/catalog/product-types",
    categories: "/catalog/categories",
    categoryTree: "/catalog/categories/tree",
    collections: "/catalog/collections",
    attributes: "/catalog/attributes",
    products: "/catalog/products",
    search: "/catalog/products/search",
    featured: "/catalog/products/featured",
    newest: "/catalog/products/new",
    refurbished: "/catalog/products/refurbished",
    product: (idOrSlug: string) => `/catalog/products/${idOrSlug}`,
    specifications: (id: string) => `/catalog/products/${id}/specifications`,
    media: (id: string) => `/catalog/products/${id}/media`,
    videos: (id: string) => `/catalog/products/${id}/videos`,
    questions: (id: string) => `/catalog/products/${id}/questions`,
  },
  cart: {
    root: "/cart",
    items: "/cart/items",
    item: (itemId: string) => `/cart/items/${itemId}`,
  },
  wishlist: {
    root: "/wishlist",
    items: "/wishlist/items",
    item: (itemId: string) => `/wishlist/items/${itemId}`,
  },
  orders: {
    list: "/orders",
    one: (idOrNumber: string) => `/orders/${idOrNumber}`,
    cancel: (id: string) => `/orders/${id}/cancel`,
    returns: (id: string) => `/orders/${id}/returns`,
    exchanges: (id: string) => `/orders/${id}/exchanges`,
    checkout: "/checkout",
    addresses: "/addresses",
    cancellationReasons: "/cancellation-reasons",
  },
  payments: {
    create: "/payments/create",
    methods: "/payments/methods",
    history: "/payments/history",
    savedMethods: "/payments/saved-methods",
    savedMethod: (id: string) => `/payments/saved-methods/${id}`,
    setDefault: (id: string) => `/payments/saved-methods/${id}/default`,
    byOrder: (orderId: string) => `/payments/order/${orderId}`,
    one: (id: string) => `/payments/${id}`,
    refunds: (id: string) => `/payments/${id}/refunds`,
    authorize: (id: string) => `/payments/${id}/authorize`,
    capture: (id: string) => `/payments/${id}/capture`,
    cancel: (id: string) => `/payments/${id}/cancel`,
    retry: (id: string) => `/payments/${id}/retry`,
  },
  shipping: {
    methods: "/shipping/methods",
    rates: "/shipping/rates",
    estimate: "/shipping/estimate",
    shipments: "/shipping/shipments",
    shipment: (id: string) => `/shipping/shipments/${id}`,
    tracking: (id: string) => `/shipping/shipments/${id}/tracking`,
    deliverySlots: "/shipping/delivery-slots",
    pickupPoints: "/shipping/pickup-points",
  },
  inventory: {
    root: "/inventory",
    stock: "/inventory/stock",
    warehouseAvailability: "/inventory/warehouse-availability",
    warehouses: "/inventory/warehouses",
    warehouse: (id: string) => `/inventory/warehouses/${id}`,
    serial: (serial: string) => `/inventory/serial/${serial}`,
  },
  marketing: {
    cmsPage: (slug: string) => `/cms/pages/${slug}`,
    blog: "/blog",
    blogPost: (slug: string) => `/blog/${slug}`,
    guides: "/guides",
    banners: "/banners",
    navigation: "/navigation",
    validateCoupon: "/coupons/validate",
    applyCoupon: "/coupons/apply",
    featureFlags: "/feature-flags",
    recommendations: "/recommendations",
    searchSuggestions: "/search/suggestions",
  },
  warranty: {
    plans: "/warranty/plans",
    check: (serial: string) => `/warranty/check/${serial}`,
    register: "/warranty/register",
    claims: "/warranty/claims",
    claim: (id: string) => `/warranty/claims/${id}`,
    rma: "/warranty/rma",
  },
  service: {
    tickets: "/service/tickets",
    job: (id: string) => `/service/jobs/${id}`,
    appointments: "/service/appointments",
  },
  analytics: {
    dashboard: "/analytics/dashboard",
    kpis: "/analytics/kpis",
    reports: "/analytics/reports",
    funnels: "/analytics/funnels",
    trends: "/analytics/trends",
    cohorts: "/analytics/cohorts",
    ltv: "/analytics/ltv",
    rfm: "/analytics/rfm",
  },
  admin: {
    orders: "/admin/orders",
    order: (id: string) => `/admin/orders/${id}`,
    orderCancel: (id: string) => `/admin/orders/${id}/cancel`,
    orderInvoice: (id: string) => `/admin/orders/${id}/invoices`,
    invoices: "/admin/orders/invoices",
    customers: "/admin/customers",
    catalogProducts: "/admin/catalog/products",
    catalogProduct: (id: string) => `/admin/catalog/products/${id}`,
    catalogVariants: "/admin/catalog/variants",
    catalogProductMedia: (id: string) => `/admin/catalog/products/${id}/media`,
    mediaUpload: "/admin/media/upload",
    inventory: "/admin/inventory",
    lowStock: "/admin/inventory/low-stock-alerts",
    payments: "/admin/payments",
    analyticsDashboard: "/admin/analytics/dashboard/refresh",
    marketingDashboard: "/admin/marketing/dashboard",
    settings: "/admin/settings",
  },
} as const;
